# Generated by Django 5.0.1 on 2024-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
